---
title: "Profile"
output: html_document
---


河村悠太 (Yuta Kawamura)

学位: 博士 (教育学)

大阪公立大学大学院現代システム科学研究科 准教授

Mail: ykawamura[at]omu.ac.jp

<a href="https://researchmap.jp/yutak/" target="_blank">Researchmap</a>  <a href="https://www.researchgate.net/profile/Yuta_Kawamura" target="_blank">ResearchGate</a>  <a href="https://scholar.google.co.jp/citations?user=YCD4gaoAAAAJ&hl=ja&oi=ao" target="_blank">Google Scholar Citations</a>
<br/><br/>

### 研究関心

利己的な側面と利他的な側面がどのように個人や社会を織りなしているのかということに関心があります。
<br/><br/>

### 学歴

2019年3月　京都大学大学院教育学研究科教育科学専攻　博士後期課程　修了

2016年4月　京都大学大学院教育学研究科教育科学専攻　博士後期課程　進学

2016年3月　京都大学大学院教育学研究科教育科学専攻　修士課程　修了

2014年4月　京都大学大学院教育学研究科教育科学専攻　修士課程　入学

2014年3月　京都大学教育学部教育科学科　卒業

2010年4月　京都大学教育学部教育科学科　入学

2010年3月　愛媛県立三島高等学校　卒業
<br/><br/>

### 職歴

2022.4 - 現在 大阪公立大学現代システム科学研究科 准教授

2021.4 - 2022.3 大阪府立大学人間社会システム科学研究科現代システム科学専攻 准教授

2019.9 - 2019.11 Visiting Researcher (University of Guelph, Canada)

2019.4 - 2021.3 日本学術振興会特別研究員PD

2016.4 - 2019.3 日本学術振興会特別研究員 DC1
<br/><br/>

### 非常勤講師, TA, RA, OA

2020.9 - 2021.3 甲南大学「尺度構成法実習」非常勤講師

2019.4 - 2019.9 神戸松蔭女子学院大学「社会心理学」非常勤講師

2019.4 - 2019.6 神戸大学「情報基礎」非常勤講師

2019.4 - 2019.6, 2020.6-2020.9 神戸大学「心理学A」非常勤講師

2018.4 - 2019.3 滋賀県立大学「行動論演習」非常勤講師

2015.1 - 2015.3 京都大学大学院教育学研究科OA

2014.6 - 2017.3 京都大学学術情報メディアセンターTA

2014.4 - 2014.9 堀川高校人間探求科社会科学ゼミTA

2014.4 - 2019.3 京都大学教育学部 教育心理学実習TA

2013.4 - 2013.11, 2015.6 - 2016.3 京都大学こころの未来研究センターOA
<br/><br/>


### 受賞歴

2024.03 日本ファンドレイジング・リサーチ大賞 優秀賞

2022.12 大阪公立大学若手研究者奨励賞 恒藤恭記念若手奨励賞

2019.12 日本人間行動進化学会 若手ポスター発表賞

2019.3 京都大学 総長賞（分野：学業）

2019.1 第9回（平成30年度）日本学術振興会 育志賞

2018.11 京都大学大学院教育学研究科長賞（分野：学業）

2016.11 日本グループ・ダイナミックス学会 2016年度優秀学会発表賞（ポスター発表部門）

2015.8 Society for Personality and Social Psychology, Graduate Travel Award ($500)

2015.1 日本社会心理学会 2014年度若手研究者奨励賞 （研究課題『「他者の目」が利他行動を減らすとき：評判への動機と規範情報に着目して』）
<br/><br/>

### 所属学会

日本心理学会

日本社会心理学会

日本人間行動進化学会

日本グループ・ダイナミックス学会

Society for Personality and Social Psychology

Human Behavior & Evolution Society
<br/><br/>

### 研究助成

2024.4 - 2028.3 日本学術振興会 科学研究費助成事業 基盤研究(B) [分担]

2022.4 - 2026.3 日本学術振興会 科学研究費助成事業 若手研究 [代表]

2021.4 - 2022.4 公益財団法人 サントリー文化財団 若手研究者のためのチャレンジ研究助成

2019.4 - 2021.3 日本学術振興会特別研究員 (PD) 特別研究員奨励費

2016.4 - 2019.3 日本学術振興会特別研究員 (DC1) 特別研究員奨励費

2015.4 - 2016.3 平成27年度京都大学デザイン学大学院連携プログラム研究助成費

2014.10 - 2015.3 平成26年度京都大学デザイン学大学院連携プログラム研究助成費
<br/><br/>

### 査読歴

Journal of Personality and Social Psychology

Journal of Experimental and Social Psychology

Personality and Social Psychology Bulletin

Social Psychological and Personality Science

European Journal of Social Psychology

Developmental Science

Current Psychology

Asian Journal of Social Psychology

Scientific Reports

Journal of Behavioral and Experimental Economics

Personality and Individual Differences

Japanese Psychological Research

Psychologia

認知科学
<br/><br/>

### 学会活動

2023.12 日本人間行動進化学会第16回大会 大会実行委員会

2023.11 - 現在 Japanese Psychological Research, Editorial Board
<br/><br/>

### 資格・免許

普通自動車一種運転免許

高等学校教員免許 (1種・数学)
<br/><br/>

### スキル
R, Python, SPSS, ArcGIS, Qualtrics, oTree, jsPsych, etc.