---
title: "Yuta Kawamura"
output: html_document
---

## Profile

Name: Yuta Kawamura (Ph.D)

Affiliation: Graduate School of Humanities and Sustainable System Sciences, Osaka Prefecture University

E-mail: kawamura[at]hs.osakafu-u.ac.jp

Research interests: Altruism, Reputation, Helping Behavior etc.

<a href="https://www.researchgate.net/profile/Yuta_Kawamura" target="_blank">ResearchGate</a>

<a href="https://scholar.google.co.jp/citations?user=YCD4gaoAAAAJ&hl=ja&oi=ao" target="_blank">Google Scholar Citations</a>
<br/><br/>

## Education

2019 Kyoto University, Ph.D. (education)

2016 Kyoto University, M.A. (education)

2014 Kyoto University, B.A. (education)
<br/><br/>

## Professional Experience

2021.4 - present Associate Professor (Osaka Prefecture University)

2019.9 - 2019.11 Visiting Researcher (University of Guelph, Canada)

2019.4 - 2021.3 Research Fellow (PD), Japan Society for the Promotion of Sciences

2016.4 - 2019.3 Research Fellow (DC1), Japan Society for the Promotion of Sciences
<br/><br/>

### TA, RA, OA, and Part-time Lecturer

2020.9 - 2021.3 Part-time Lecturer (Scaling Training), Konan University

2019.4 - 2019.9 Part-time Lecturer (Social Psychology), Kobe Shoin Women's University

2019.4 - 2019.6 Part-time Lecturer (Basic Information), Kobe University

2019.4 - 2019.6, 2020.6-2020.9 Part-time Lecturer (Psychology A), Kobe University

2018.4 - 2019.3 Part-time Lecturer (Research Methods for the Studies of Human Behaviors), The University of Shiga Prefecture

2015.1 - 2015.3 Office Assistant, Graduate School of Education, Kyoto University

2014.6 - 2017.3 Teaching Assistant, Academic Center for Computing and Media Studies, Kyoto University 

2014.4 - 2014.9 Teaching Assistant, Horikawa High School

2014.4 - 2019.3 Teaching Assistant, Graduate School of Education, Kyoto University

2013.4 - 2013.11, 2015.6-2016.3 Office Assistant, Kokoro Research Center, Kyoto University
<br/><br/>

## Fellowship

2021.4 - 2022.3 Grant for Groundbreaking Young Researchers, Suntory Foundation (1,000,000 yen)

2019.4 - 2021.3 Research Fellowship for Young Scientists (PD), Japan Society for the Promotion of Science (2,500,000 yen)

2016.4 - 2019.3 Doctoral Course Fellowship, Japan Society for the Promotion of Science (2,800,000 yen)

2015.4 - 2016.3 Research Grant, Kyoto University Design School - Collaborative Graduate Program in Design (1,200,000 yen)

2014.10 - 2015.3 Research Grant, Kyoto University Design School - Collaborative Graduate Program in Design (600,000 yen)
<br/><br/>

## Awards

2019 Human Behavior & Evolution Society of Japan, Distinguished Presentation Award

2019 Kyoto University, President's Award (100,000 yen)

2019 Japan Society for the Promotion of Science, Ninth JSPS Ikushi Prize (1,100,000 yen)

2018 Graduate School of Education (Kyoto University), Distinguished Student Award

2016 Japanese Group Dynamics Association, Distinguished Presentation Award

2015 Society for Personality and Social Psychology, Graduate Travel Award ($ 500)

2014 Japanese Society for Social Psychology, Encouraging Prize for Young Researchers (100,000 yen)
<br/><br/>

## Professional Membership

Society for Personality and Social Psychology

Japanese Psychological Association

Japanese Society of Social Psychology

Japanese Group Dynamics Association

Human Behavior & Evolution Society of Japan

Human Behavior & Evolution Society
<br/><br/>

## Publications

### Journal Articles (Peer-Reviewed Articles)
1. Himichi, T., Osanai, H., Goto, T., Fujita, H., <u>Kawamura, Y.</u>, Smith, A. R., & Nomura, M. (2021). Exploring the Multidimensional Links between Trait Mindfulness and Trait Empathy. Frontiers in Psychiatry, 12, 498614.

1. <u>Kawamura, Y.</u>, Ohtsubo, Y., & Kusumi, T. (2021). Effects of Cost and Benefit of Prosocial Behavior on Reputation. Social Psychological and Personality Science, 12(4), 452-460. doi: <a href="https://doi.org/10.1177/1948550620929163" target="_blank">10.1177/1948550620929163</a>

1. <u>Kawamura, Y.</u>, Kusumi, T. (2020). Altruism does not always lead to a good reputation: A normative explanation. Journal of Experimental Social Psychology, 90, 104021. doi: <a href="https://www.sciencedirect.com/science/article/pii/S0022103120303619" target="_blank">10.1016/j.jesp.2020.104021</a>

1. Goto, T., Ichimura, K., Oka, R., <u>Kawamura, Y.</u>, & Kusumi, T. (2019). Trait-related Concepts Activate Stereotypically Consistent Concepts on the Same Stereotype Dimension, but may not Spread to the Other Stereotype Dimension. Japanese Psychological Research, 61(2), 83-93. doi: <a href="https://doi.org/10.1111/jpr.12247" target="_blank">10.1111/jpr.12247</a>

1. Uchida, Y., Takemura, K., Fukushima, S., Saizen, I., <u>Kawamura, Y.</u>, Hitokoto, H., Koizumi, N., & Yoshikawa, S. (2019). Farming cultivates a community-level shared culture through collective activities: Examining contextual effects with multilevel analyses. Journal of Personality and Social Psychology, 116(1), 1-14. doi: <a href="https://dx.doi.org/10.1037/pspa0000138" target="_blank">10.1037/pspa0000138</a>

1. Ichimura, K., <u>Kawamura, Y.</u>, Takahashi, Y., Kusumi, T. (2018). Relationships between Environmental Factors of the Learning
Commons and Creativity Task Performance. Japanese Journal of Educational Technology, 42(1), 55-64. doi: <a href="https://doi.org/10.15077/jjet.42015" target="_blank">10.15077/jjet.42015</a> (in Japanese with English Abstract)

1. <u>Kawamura, Y.</u>, Kusumi, T. (2018). The relationship between rejection avoidance and altruism is moderated by social norms. Personality and Individual Differences, 129, 24-27. doi: <a href="https://doi.org/10.1016/j.paid.2018.02.038" target="_blank">10.1016/j.paid.2018.02.038</a>

1. <u>Kawamura, Y.</u>, Kusumi, T. (2018). Relationships between two types of reputational concern and altruistic behavior in daily life. Personality and Individual Differences, 121, 19-24. doi: <a href="https://doi.org/10.1016/j.paid.2017.09.003" target="_blank">10.1016/j.paid.2017.09.003</a>

1. <u>Kawamura, Y.</u>, Kusumi, T. (2017). Selfishness is attributed to men who help young women: Signaling function of male altruism. Letters on Evolutionary Behavioral Science, 2, 45-48. doi: <a href="https://doi.org/10.5178/lebs.2017.64" target="_blank">10.5178/lebs.2017.64</a>

1. <u>Kawamura, Y.</u>, Kusumi, T. (2017). The norm-dependent effect of watching eyes on donation. Evolution and Human Behavior, 38, 659-666. doi: <a href="https://doi.org/10.1016/j.evolhumbehav.2017.05.003" target="_blank">10.1016/j.evolhumbehav.2017.05.003</a>

1. Himichi, T., Osanai, H., Goto, T., Fujita, H., <u>Kawamura, Y.</u>, Davis, M. H., & Nomura, M. (2017).  Development of a Japanese version of the Interpersonal Reactivity Index. Japanese Journal of Psychology, 88(1), 61-71. doi: <a href="https://doi.org/10.4992/jjpsy.88.15218" target="_blank">10.4992/jjpsy.88.15218</a> (in Japanese with English Abstract)

1. <u>Kawamura, Y.</u>, Kusumi, T. (2015). The effects of charity advertising on donations and donors’ explicit and implicit evaluations of recipients. Japanese Journal of Psychology, 86 (1), 21-31. doi: 
<a href="https://doi.org/10.4992/jjpsy.86.14021" target="_blank">10.4992/jjpsy.86.14021</a> (in Japanese with English Abstract)
<br/><br/>

### Journal Articles (Non Peer-Reviewed Articles)

None
<br/><br/>

### Presentations (at International Conferences)

1. <u>Kawamura, Y.</u>, Ohtsubo, Y., & Kusumi, T. (2019, 10). Effects of Cost and Benefit of Altruism on Reputation. The annual Darwin Day meeting, St. Catharines, ON, Canada, October 15. 

1. <u>Kawamura, Y.</u>, Kusumi, T. (2016, 8). Effort to Buy a Gift Affects Estimates of Recipients' Appreciation. The 23rd Congress of the International Association for Cross-Cultural Psychology, Nagoya, Japan, July 30- August 3.

1. <u>Kawamura, Y.</u>, Kusumi, T. (2016, 7). Age differences in the relationship between the Big-Five personality traits and altruistic behavior. The 31st International Congress of Psychology, Yokohama, Japan, July 24-29.

1. Himichi, T., Osanai, H., Goto, T., Fujita, H., <u>Kawamura, Y.</u>, & Nomura, M. (2016, 7). Relationships between mindfulness and empathy. The 31st International Congress of Psychology, Yokohama, Japan, July 24-29.

1. <u>Kawamura, Y.</u>, Kusumi, T. (2016, 1). The effect of reputational concerns on altruistic behavior. The 17th Annual Meeting of Society for Personality and Social Psychology, San Diego, California, USA, January 28-30. (granted SPSP Student Travel Award)

1. Himichi, T., Fujita, H., Masuda, M., <u>Kawamura, Y.</u>, Hiraoka, D., & Nomura, M. (2016, 1). Domain specific effects of negative emotions on lateral prefrontal cortex activity during inference of others’ mind. The 17th Annual Meeting of Society for Personality and Social Psychology, San Diego, California, USA, January 28-30.

1. <u>Kawamura, Y.</u>, Kusumi, T. (2015, 2). Gender differences in the evaluation of men's altruistic behavior. The 14th Justice and Morality Preconference (at the 16th Annual Meeting of Society for Personality and Social Psychology), Long Beach, California, USA, February 26.

1. Uchida, Y., Takemura, K., Fukushima, S., Saizen, I., Koizumi, N., <u>Kawamura, Y.</u>, & Yoshikawa, S. (2015, 2). Farming, but not fishing, cultivates shared culture within a community. The 10th Cultural Psychology Preconference (at the 16th Annual Meeting of Society for Personality and Social Psychology), Long Beach, California, USA, February 26.
<br/><br/>


