---
title: "Lab"
output: html_document
---

本研究室では，ヒトの向社会性・利他性を中心に，様々な心理・社会的現象について社会心理学・進化心理学的な視点から研究しています。進学やポスドクに関心のある方は，ykawamura[at]omu.ac.jpまでお気軽にご連絡ください。
<br/><br/>

### Lab News

ラボメンバーのかかわった研究成果や助成・受賞をまとめています。

<div class="lab-news">

- 2025.4 Cleone Mitsuiさんが日本学術振興会特別研究員DC2に採用されました

- 2025.3 三石宏大さんが大阪公立大学2024年度後期学長表彰を受賞しました <a href="https://www.omu.ac.jp/info/news/entry-16813.html" target="_blank">[link]</a>

- 2025.3 川口周一郎さんが大阪公立大学2024年度研究業績優秀表彰を受賞しました <a href="https://www.omu.ac.jp/info/news/entry-16813.html" target="_blank">[link]</a>

- 2025.2 Cleone MitsuiさんがThe 25th Annual Convention of Society for Personality and Social Psychologyで発表しました

- 2025.1 Cleone Mitsuiさんが計量・数理政治学会（JSQPS）2025年冬季集会で発表しました

- 2024.12 三石宏大さんが日本人間行動進化学会第16回大会で発表しました

- 2024.11 川口周一郎さんが大阪公立大学2024年度前期学長表彰を受賞しました <a href="https://www.omu.ac.jp/info/news/entry-14148.html" target="_blank">[link]</a>

- 2024.11 論文が出版されました <a href="https://www.sciencedirect.com/science/article/pii/S0022103124001082?dgcid=coauthor" target="_blank">(Mitsuishi & Kawamura, 2025)</a>

- 2024.10 論文が出版されました <a href="https://rdcu.be/dXE7B" target="_blank">(Kawaguchi & Kawamura, 2024)</a>

- 2024.10 Cleone Mitsuiさんが松下幸之助記念志財団2024年度研究助成の助成対象者に選ばれました <a href="https://matsushita-konosuke-zaidan.or.jp/works/research/promotion_research_02_index.html" target="_blank">[link]</a>

- 2024.8 伊藤颯希さん，三石宏大さん，川口周一郎さん，Cleone Mitsuiさんが日本社会心理学会第64回大会で発表しました

- 2024.7 三石宏大さんが第27回実験社会科学カンファレンスで発表しました

- 2024.1 論文が出版されました <a href="https://doi.org/10.1111/jpr.12507" target="_blank">(Kawamura & Totake, in press)</a>

- 2024.1 川口周一郎さんが2023年度日本社会心理学会若手研究者奨励賞を受賞しました <a href="https://www.socialpsychology.jp/award/wakate/" target="_blank">[link]</a>

- 2023.12 三石宏大さんが日本人間行動進化学会第16回大会で発表しました

- 2023.9 川口周一郎さんが日本社会心理学会第64回大会で発表しました

- 2023.3 論文が出版されました <a href="https://doi.org/10.5178/lebs.2023.102" target="_blank">(Kawai & Kawamura, 2023)</a>
<br/>

</div>
<br/><br/>

### 現在のメンバー

大学院

- D2　Cleone Mitsui

- M2　伊藤 颯希　三石 宏大

- M1　奈良岡 愛梨

学部

- 4年生 3名

<br/><br/>

### 大学院OB/OG

- 2025.3修了　川口 周一郎

<br/><br/>

### 過去の修論タイトル

2024年度

- 効果的利他主義の心理的メカニズム: 寄付効果の認識と共感に着目して

<br/><br/>

### 過去の卒論タイトル

関連研究が出版されている場合はリンクをつけています。

2024年度

- 向社会的デマが拡散者の印象評価に及ぼす影響

- 命てんでんこへの態度と関連する心理・社会的要因とは

- 視点取得は恩義せがましい援助の印象に影響を与えるか

- 日本とアメリカの映画ポスターにおける文化比較 ―時間による文化の変容－

2023年度

- 目標関連思考によるマインドワンダリングは計画によって解消されるか

- 声の調子と発話内容が信頼行動に及ぼす影響

- 日米の映画ポスターにおける情報量の文化差

- 援助要請を妨げる心理的要因の検討

- 人は罰場面を回避するのか？―場面選択型第三者罰ゲームを用いた検討― <a href="https://www.sciencedirect.com/science/article/pii/S0022103124001082" target="_blank">[link]</a>

2022年度

- 日本における集団間共感バイアスについての検討 <a href="https://doi.org/10.5178/lebs.2023.102" target="_blank">[link]</a>

- 共同収奪ゲームにおける競争的利他主義の検討 <a href="https://rdcu.be/dXE7B" target="_blank">[link]</a>

- 男性の育休取得に関する社会的変化と心理的要因の関連 <a href="https://onlinelibrary.wiley.com/doi/full/10.1111/jpr.12507" target="_blank">[link]</a>
<br/><br/>


